### ISSUE TITLE
There is no way to setup the node 

### ISSUE THREAD

**Issue by ThaYTOfficial** [Plexactyl/panel#1]
[api.client.locations.1]
name = "DE"

**Comment by KingTino104** [comment]
Locations are locations on Pterodactyl. Whats the issue here?

```
[api.client.locations.1]
name = "Germany"

[api.client.locations.2]
name = "India"

[api.client.locations.3]
name = "Singapore"
```

This is how it should look when you have multiple locations.

**Comment by ThaYTOfficial** [comment]
> An error has occured while attempting to update your account information and server list.

what is this error Bruh when creating server

![image](https://github.com/user-attachments/assets/a137f325-257f-43c7-8443-5e096e5c08d2)

**Comment by KingTino104** [comment]
Your confiugration isn't correct. It works fine for me.

**Comment by ThaYTOfficial** [comment]
> Your confiugration isn't correct. It works fine for me.

can you send me a default config of urs so I cant copy it

**Comment by KingTino104** [comment]
https://github.com/Plexactyl/panel/blob/v18/config-example.toml

**Comment by ThaYTOfficial** [comment]
not works bruh. update the dash
