### ISSUE TITLE
AFK Page not working

### ISSUE THREAD

**Issue by Timor2011Pro** [Plexactyl/panel#12]
![image](https://github.com/user-attachments/assets/6093c7af-7b29-4d8a-a1f2-af937518f2a3)

This pop-up appears on my screen every time I try to access the AFK page. This causes the AFK page to no longer work. Does anyone have the same problem or a fix? (sorry for the dutch above)

**Comment by KingTino104** [comment]
You shall check your nginx configuration.

**Comment by Timor2011Pro** [comment]
What should I look for because I am using the standard config.

**Comment by KingTino104** [comment]
![image](https://github.com/user-attachments/assets/223e8d5f-d431-4022-b54f-613a62b3745f)
If this is not your websocket path in the config, thats why.

**Comment by Timor2011Pro** [comment]
I just fixed it by changing the location in the nginx config from /afk/ws to /ws and the proxy pass from ..../afk/ws to ..../ws! Thanks for helping.
