### ISSUE TITLE
Add renewal Page

### ISSUE THREAD

**Issue by NIGHTGAMER95** [Plexactyl/panel#13]
So many user dosen't upgrade there service adding a renewal system will help us to get funds on linkvertise to run our free host service can you please add renewal system

**Comment by KingTino104** [comment]
not happening

**Comment by NIGHTGAMER95** [comment]
Why not?

**Comment by KingTino104** [comment]
use another dashboard if u want that feature

**Comment by NIGHTGAMER95** [comment]
Can you give me a sugggestion for it? not heliactyl tho

**Comment by Sobble2546** [comment]
it would be cool if u can add it as a option
