### ISSUE TITLE
Error with certbot

### ISSUE THREAD

**Issue by ElPerrosss** [Plexactyl/panel#15]
I have this error:

-----------------
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for client.bytehosting.us

Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: client.bytehosting.us
  Type:   dns
  Detail: DNS problem: NXDOMAIN looking up A for client.bytehosting.us - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for client.bytehosting.us - check that a DNS record exists for this domain

Hint: The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
----------------

In my vps I already have a ssl for my pterodactyl panel with cloudflare, but first the error was something related to port 80, how could I fix that?

**Comment by KingTino104** [comment]
Certbot is not my service.
