### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by mizuo-san** [Plexactyl/panel#4]
![image](https://github.com/user-attachments/assets/ace06afa-5f24-4a99-8bdb-286c5b81ead8)
Problem on my side or problem in Plexactyl?

**Comment by KingTino104** [comment]
whitelist your webserver's ip from cloudflare

**Comment by mizuo-san** [comment]
Is it important? Is it possible somehow not to use cloudflare?

**Comment by KingTino104** [comment]
well are you using cloudflare?

**Comment by mizuo-san** [comment]
No, I don't use it

**Comment by KingTino104** [comment]
is your pterodactyl api key correct

**Comment by mizuo-san** [comment]
Yes

**Comment by KingTino104** [comment]
try curling your panel url from the VPS terminal (curl https://panel.example.com)

and send the output

**Comment by mizuo-san** [comment]
`<!doctype html>
<html>
<head>
    <title>Project An-Pan</title>
    <link rel="icon" type="image/x-icon" href="https://avatars.githubusercontent.com/u/176057729">
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://unpkg.com/@popperjs/core@2.10.1/dist/umd/popper.min.js"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
<body style="font-family: 'Inter'">
<div class="relative isolate overflow-hidden bg-white">
  <svg class="absolute inset-0 -z-10 h-full w-full stroke-gray-200 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]" aria-hidden="true">
    <defs>
      <pattern id="0787a7c5-978c-4f66-83c7-11c213f99cb7" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
        <path d="M.5 200V.5H200" fill="none" />
      </pattern>
    </defs>
    <rect width="100%" height="100%" stroke-width="0" fill="url(#0787a7c5-978c-4f66-83c7-11c213f99cb7)" />
  </svg>
  <div class="mx-auto max-w-7xl px-6 pt-20 sm:pb-32 lg:flex lg:py-30 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-xl lg:flex-shrink-0 lg:pt-8">
      <img class="h-11" src="https://avatars.githubusercontent.com/u/176057729" alt="Logo">
      <h1 class="mt-10 text-xl font-semibold tracking-tight text-gray-800 sm:text-6xl">Your #1 platform for hosting a Minecraft server, at no cost.</h1>
      <p class="mt-6 text-lg leading-8 tracking-tught text-gray-600">Everything you need for your project - fast and easy. Deploy a free container, game server or service in under 60 seconds. </p>
      <div class="mt-10 flex items-center gap-x-6">
        <a href="/cp/login" class="rounded-xl bg-gray-600 transition px-5 py-2 text-base font-medium leading-7 text-white shadow-sm hover:bg-gray-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-600">Sign in</a>
    </div>
    </div>
  </div>
</div>
</body>
</html>root@v22315:~# curl http://panel.project-anpan-test.xyz:1025/

<!doctype html>
<html>
<head>
    <title>Project An-Pan</title>
    <link rel="icon" type="image/x-icon" href="https://avatars.githubusercontent.com/u/176057729">
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://unpkg.com/@popperjs/core@2.10.1/dist/umd/popper.min.js"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
<body style="font-family: 'Inter'">
<div class="relative isolate overflow-hidden bg-white">
  <svg class="absolute inset-0 -z-10 h-full w-full stroke-gray-200 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]" aria-hidden="true">
    <defs>
      <pattern id="0787a7c5-978c-4f66-83c7-11c213f99cb7" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
        <path d="M.5 200V.5H200" fill="none" />
      </pattern>
    </defs>
    <rect width="100%" height="100%" stroke-width="0" fill="url(#0787a7c5-978c-4f66-83c7-11c213f99cb7)" />
  </svg>
  <div class="mx-auto max-w-7xl px-6 pt-20 sm:pb-32 lg:flex lg:py-30 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-xl lg:flex-shrink-0 lg:pt-8">
      <img class="h-11" src="https://avatars.githubusercontent.com/u/176057729" alt="Logo">
      <h1 class="mt-10 text-xl font-semibold tracking-tight text-gray-800 sm:text-6xl">Your #1 platform for hosting a Minecraft server, at no cost.</h1>
      <p class="mt-6 text-lg leading-8 tracking-tught text-gray-600">Everything you need for your project - fast and easy. Deploy a free container, game server or service in under 60 seconds. </p>
      <div class="mt-10 flex items-center gap-x-6">
        <a href="/cp/login" class="rounded-xl bg-gray-600 transition px-5 py-2 text-base font-medium leading-7 text-white shadow-sm hover:bg-gray-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-600">Sign in</a>
    </div>
    </div>
  </div>
</div>
</body>
</html>`

**Comment by mizuo-san** [comment]
oh

**Comment by KingTino104** [comment]
your panel url, not dashboard url

also please format it as code

**Comment by mizuo-san** [comment]
https://pastecode.io/s/ba4qsaz0

**Comment by mizuo-san** [comment]
Finally i can format it on github
``` <!DOCTYPE html>
<html>
    <head>
        <title>Pterodactyl</title>

                    <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
            <meta name="csrf-token" content="lkWgebDUBqDO2PL7aVKxFpQlkPj8usHL7ZaAtIlA">
            <meta name="robots" content="noindex">
            <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
            <link rel="icon" type="image/png" href="/favicons/favicon-32x32.png" sizes="32x32">
            <link rel="icon" type="image/png" href="/favicons/favicon-16x16.png" sizes="16x16">
            <link rel="manifest" href="/favicons/manifest.json">
            <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#bc6e3c">
            <link rel="shortcut icon" href="/favicons/favicon.ico">
            <meta name="msapplication-config" content="/favicons/browserconfig.xml">
            <meta name="theme-color" content="#0e4688">

                                                <script>
                    window.SiteConfiguration = {"name":"Pterodactyl","locale":"en","recaptcha":{"enabled":true,"siteKey":"6LcJcjwUAAAAAO_Xqjrtj9wWufUpYRnK6BW8lnfn"}};
                </script>
                            <style>
            @import url('//fonts.googleapis.com/css?family=Rubik:300,400,500&display=swap');
            @import url('//fonts.googleapis.com/css?family=IBM+Plex+Mono|IBM+Plex+Sans:500&display=swap');
        </style>


            </head>
    <body class="bg-neutral-800">
                                    <div id="modal-portal"></div>
    <div id="app"></div>
                                        <script src="/assets/bundle.9f9de542.js" crossorigin="anonymous"></script>
            </body>
</html>
 ```

**Comment by KingTino104** [comment]
your panel API key is invalid, did you give it all permissions as read and write?

**Comment by mizuo-san** [comment]
Yes, now I will just restart panel, wings and create new api key and give you answer.

**Comment by mizuo-san** [comment]
Finally the problem is solved, thank you very much!
